/*
 * Vencord, a Discord client mod
 * Copyright (c) 2025 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

const defaultAbbreviations = new Map(
    Object.entries({
        tbh: "to be honest",
        tbf: "to be fair",
        rly: "really",
        jk: "just kidding",
        pb: "personal best",
        wr: "world record",
        wth: "what the hell",
        omg: "oh my god",
        idk: "i dont know",
        fr: "for real",
        tba: "to be announced",
        tmi: "too much information",
        iirc: "if i recall correctly",
        imo: "in my opinion",
        rn: "right now",
        atm: "at the moment",
        oomf: "one of my friends",
        iykyk: "if you know you know",
        yk: "you know",
        yolo: "you only live once",
        tldr: "to long; didnt read",
        idc: "i dont care",
        afaik: "as far as i know",
        afk: "away from keyboard",
        aka: "also known as",
        grwm: "get ready with me",
        fb: "facebook",
        ig: "instagram",
        snap: "snapchat",
        yt: "youtube",
        twt: "twitter / crying kaomoji",
        dm: "direct message",
        pm: "private message",
        irl: "in real life",
        nsfw: "not safe for work",
        sfw: "safe for work",
        lol: "laugh out loud",
        ily: "i love you",
        hbu: "how about you",
        hru: "how are you",
        rofl: "rolling on floor laughing",
        eta: "estimated time of arrival",
        wyd: "what are you doing",
        gm: "good morning",
        gn: "good night",
        ttys: "talk to you soon",
        bc: "because",
        bff: "best friends forever",
        bf: "boyfriend",
        gf: "girlfriend",
        bsf: "bestfriend",
        goat: "greatest of all time",
        fyi: "for your information",
        hbd: "happy birthday",
        omw: "on my way",
        btw: "by the way",
        asap: "as soon as possible",
        np: "no problem",
        yw: "youre welcome",
        gtg: "got to go",
        lmk: "let me know",
        dni: "do not interact",
        dniuid: "do not interact unless i do",
        dniuc: "do not interact unless close (friend)",
        iwec: "interact with extreme caution",
        iwc: "interact with caution",
        int: "integer",
        pov: "point of view",
        msg: "message",
        smh: "shaking my head",
        asl: "american sign language",
        bsl: "british sign language",
        gl: "good luck",
        brb: "be right back",
        diy: "do it yourself",
        ppl: "people",
        op: "original poster",
        oc: "original character/content",
        cya: "see you later",
        eol: "end of life",
        gg: "good game",
        nm: "not much",
        so: "significant other",
        tos: "terms of service",
        ty: "thank you",
        tysm: "thank you so much",
        dw: "dont worry",
    }),
);

export default defaultAbbreviations;
