export const enum QuestTaskType {
    STREAM_ON_DESKTOP = "STREAM_ON_DESKTOP",
    PLAY_ON_DESKTOP = "PLAY_ON_DESKTOP",
    PLAY_ON_DESKTOP_V2 = "PLAY_ON_DESKTOP_V2",
    PLAY_ON_XBOX = "PLAY_ON_XBOX",
    PLAY_ON_PLAYSTATION = "PLAY_ON_PLAYSTATION",
    PLAY_ACTIVITY = "PLAY_ACTIVITY",
    WATCH_VIDEO = "WATCH_VIDEO",
    WATCH_VIDEO_ON_MOBILE = "WATCH_VIDEO_ON_MOBILE",
    ACHIEVEMENT_IN_GAME = "ACHIEVEMENT_IN_GAME",
    ACHIEVEMENT_IN_ACTIVITY = "ACHIEVEMENT_IN_ACTIVITY"
}

export const enum QuestRewardType {
    CODE = 1,
    COSMETIC = 3,
    ORBS = 4
}

export const enum QuestFeature {
    GIFT_INVENTORY_SETTINGS_BADGE = 0,
    QUEST_BAR = 1,
    QUEST_INVENTORY_CARD = 2,
    QUESTS_EMBED = 3,
    ACTIVITY_PANEL = 4,
    QUEST_LIVE_STREAM = 5,
    MEMBERS_LIST = 6,
    QUEST_BADGE = 7,
    GIFT_INVENTORY_FOR_YOU = 8,
    GIFT_INVENTORY_OTHER = 9,
    QUEST_BAR_V2 = 10,
    QUEST_HOME_DESKTOP = 11,
    QUEST_HOME_MOBILE = 12,
    QUEST_BAR_MOBILE = 13,
    THIRD_PARTY_APP = 14,
    QUEST_BOTTOM_SHEET = 15,
    QUEST_EMBED_MOBILE = 16,
    QUEST_HOME_MOVE_CALLOUT = 17,
    DISCOVERY_SIDEBAR = 18,
    QUEST_SHARE_LINK = 19,
    CONNECTIONS_MODAL = 20,
    DISCOVERY_COMPASS = 21,
    TROPHY_CASE_CARD = 22,
    VIDEO_MODAL = 23,
    VIDEO_MODAL_END_CARD = 24,
    REWARD_MODAL = 25,
    EXCLUDED_QUEST_EMBED = 26,
    VIDEO_MODAL_MOBILE = 27,
    ORBS_ANNOUNCEMENT_MODAL = 28,
    ORBS_BALANCE_MENU = 29,
    QUEST_ENROLLMENT_BLOCKED_BOTTOM_SHEET = 30,
    ORBS_SHOP_HERO_CTA = 31,
    QUEST_ENROLLMENT_BLOCKED_MODAL = 32,
    INTERNAL_PREVIEW_TOOL = 33,
    ORBS_REHEAT_COACHMARK_CTA = 34,
    INVALID_QUEST_EMBED = 35,
    NOT_SHAREABLE_QUEST_EMBED = 36,
    QUEST_HOME_MOVE_CALLOUT_DISCOVER = 37,
    SPONSORED_QUEST_SHEET = 38,
    MOBILE_ORBS_ONBOARDING_DC = 39,
    RUNNING_ACTIVITY = 40,
    VIDEO_MODAL_PRIMARY_CTA = 41,
    QUEST_HOME_TAKEOVER = 42
}

export const enum QuestStatus {
    UNENROLLED = "UNENROLLED",
    ENROLLED = "ENROLLED",
    CLAIMED = "CLAIMED"
}

export const enum QuestRewardAssignmentMethod {
    DIRECT = 1
}

export const enum QuestPlatform {
    DESKTOP = 0
}

export const enum QuestSharePolicy {
    SHAREABLE_EVERYWHERE = "shareable_everywhere"
}

export const enum QuestJoinOperator {
    OR = "or"
}

export const enum QuestConfigVersion {
    V2 = 2
}
