name: Release
on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    FORCE_COLOR: true

permissions:
    contents: write

jobs:
    Build:
        uses: ./.github/workflows/build-reusable.yml
        with:
            upload-target: 'latest'
        secrets:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ETOKEN: ${{ secrets.ETOKEN }}
