name: NixOS Build
on:
    workflow_dispatch:
    schedule:
        - cron: 0 0 * * *

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    FORCE_COLOR: true

permissions:
    contents: write

jobs:
    GetDate:
        runs-on: ubuntu-latest
        outputs:
            date: ${{ steps.date.outputs.date }}
        steps:
            - name: Get current date
              id: date
              run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    Build:
        needs: GetDate
        uses: ./.github/workflows/build-reusable.yml
        with:
            upload-target: 'dated'
            release-tag: ${{ needs.GetDate.outputs.date }}
        secrets:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
