name: PR Auto Update Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # PR Auto Update action
      - name: PR Auto Update
        uses: RomuloLim/auto-pr-action@v1.0.0-beta
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
